### PR TITLE
[Editorial] Eliminate subchapter numbers

### PR DESCRIPTION
**Pull request by chapkachapka**
Richardson eliminated the numbering of subchapters in later editions, and in all editions of some later volumes. This pull request replaces the numbered subchapters with unnumbered thought breaks, as the author later preferred, and to ensure consistency across all published volumes.

### CODE REVIEW

**Comment by acabal** [comment]
If we're keeping sub `<section>`s, then `<hr/>` is not necesary because the section already implies a thematic break. So, you should remove `<hr/>` and add CSS to put dividing lines between `<section>`s instead.

**Comment by chapkachapka** [comment]
I kept the subsections because it was easier to keep than delete them, but
they don't serve any real purpose right now, and I'm having a lot of
trouble figuring out a consistent, well-supported way to add a line after a
<section>.

I'm thinking it might make more sense to take the <section> tags out rather
than taking the <hr> tags out--this would also have the benefit that the
thought breaks would look consistent with other SE editions. Any objection?

Chris

**Comment by acabal** [comment]
The question is, are those sections subchapters, or is it a single chapter with thematic breaks? That will inform your decision.

**Comment by chapkachapka** [comment]
I think it's closer to thematic breaks. At times it's literally just a new
train of thought in an internal monologue. If that's the test I think
they're definitely on the thematic break side. The chapters feel
self-contained, but the smaller divisions don't.

--Chris

**Comment by acabal** [comment]
OK, so this PR needs to be updated to match that understanding then

**Comment by chapkachapka** [comment]
Updated.

**Comment by acabal** [comment]
Great, thanks!

**Pull request merged**
